"use client";
import { useEffect, useRef, useState } from "react";
import { rpc, type Template } from "../../lib/data";
import { errorMessage, parseReward } from "../../lib/rules";
import { uploadBountyImages } from "../../lib/marketplace";
import { track } from "../../lib/metrics";
const initial={template:"",title:"",description:"",criteria:"",minutes:"30",mode:"remote",location:"",privateLocation:"",due:"",reward:""};
export function PostForm({catalog,balance,userId,onPublished}:{catalog:Template[];balance:number|null;userId:string;onPublished:(id:string,warning?:string)=>Promise<void>}){
 const [draft,D]=useState(initial),[step,S]=useState(1),[error,E]=useState(""),[busy,B]=useState(false),[files,F]=useState<File[]>([]),[restored,R]=useState(false);
 const key=useRef<string>("");
 useEffect(()=>{track(`post_step_${step}` as "post_step_1"|"post_step_2"|"post_step_3");},[step]);
 useEffect(()=>{try{const stored=sessionStorage.getItem(`bounty:draft:${userId}`);if(stored)D({...initial,...JSON.parse(stored)});}catch{}R(true);},[userId]);
 useEffect(()=>{if(restored)sessionStorage.setItem(`bounty:draft:${userId}`,JSON.stringify(draft));},[draft,restored,userId]);
 const template=catalog.find(t=>t.id===draft.template);
 function change(name:keyof typeof initial,value:string){D(d=>({...d,[name]:value}));key.current="";}
 async function submit(e:React.FormEvent){e.preventDefault();E("");if(step<3){try{if(step===2){const reward=parseReward(draft.reward);if(balance===null||reward>balance)throw new Error("The reward exceeds your available credits.");}S(step+1);}catch(e){E(errorMessage(e));}return;}B(true);
  try{if(!template)throw new Error("Select a current approved task template.");const reward=parseReward(draft.reward);if(!key.current)key.current=crypto.randomUUID();
   const id=await rpc<string>("create_bounty_v2",{p_template:template.id,p_title:draft.title,p_description:draft.description,p_reward:reward,p_criteria:draft.criteria,p_minutes:Number(draft.minutes),p_location_type:draft.mode,p_location:draft.mode==="campus"?draft.location:null,p_private_location:draft.mode==="campus"?draft.privateLocation:null,p_due:draft.due?new Date(draft.due).toISOString():null,p_request:key.current});
   sessionStorage.removeItem(`bounty:draft:${userId}`);
   // Publishing is already committed. An attachment failure must not invite a duplicate post.
   if(files.length){try{await uploadBountyImages(id,files);}catch{await onPublished(id,"Your bounty was published, but one or more photos could not be uploaded. You can add them from its detail page.");return;}}
   await onPublished(id);
  }catch(e){E(errorMessage(e));}finally{B(false);}
 }
 return <section className="page-shell"><p className="eyebrow">POST A BOUNTY · STEP {step} OF 3</p><div className="page-title"><div><h1>{step===1?"What do you need a hand with?":step===2?"Make it worth their while.":"One last look."}</h1><p>Your draft stays in this browser tab until you publish or sign out.</p></div></div><ol className="progress-steps">{["Describe","Timing & reward","Review"].map((s,i)=><li aria-current={step===i+1?"step":undefined} key={s}>{i+1}. {s}</li>)}</ol><form onSubmit={submit} className="post-layout"><div className="panel">
 {step===1&&<><label>Approved task type<select required value={draft.template} onChange={e=>{const t=catalog.find(t=>t.id===e.target.value);D({...draft,template:e.target.value,title:t?.title||"",reward:String(t?.default_reward_credits||""),mode:t?.requires_location?"campus":"remote"});key.current="";}}><option value="">Choose a task type</option>{catalog.map(t=><option key={t.id} value={t.id}>{t.category} · {t.title}</option>)}</select></label>{!catalog.length&&<p>No templates are available. Your university verification and the database configuration must be complete before posting.</p>}{template&&<aside className="recommendation"><p>{template.guidance}</p><small>Relevant skills: {template.required_skills.join(", ")}</small></aside>}<label>Task title<input required minLength={5} maxLength={120} value={draft.title} onChange={e=>change("title",e.target.value)} placeholder="What result do you need?"/></label><label>Details<textarea required minLength={20} maxLength={3000} rows={5} value={draft.description} onChange={e=>change("description",e.target.value)} placeholder="Explain the work, useful context, and what is included."/></label><label>What does completion look like?<textarea required maxLength={1000} value={draft.criteria} onChange={e=>change("criteria",e.target.value)} placeholder="For example: 30 minutes of feedback and three practical improvements."/></label><small>Learning support is welcome. Completing assessed work for someone else is not.</small></>}
 {step===2&&<><div className="field-row"><label>Estimated minutes<input type="number" min="5" max="1440" required value={draft.minutes} onChange={e=>change("minutes",e.target.value)}/></label><label>Location type<select value={draft.mode} onChange={e=>change("mode",e.target.value)}><option value="remote" disabled={template?.requires_location}>Remote</option><option value="campus">On campus</option></select></label></div>{draft.mode==="campus"&&<><label>Broad campus location<input required maxLength={120} value={draft.location} onChange={e=>change("location",e.target.value)} placeholder="e.g. Powell Library"/></label><label>Private meeting details (optional)<input maxLength={300} value={draft.privateLocation} onChange={e=>change("privateLocation",e.target.value)}/></label><small>Only you and the selected helper can read exact meeting details.</small></>}<label>Deadline (optional, your local time)<input type="datetime-local" value={draft.due} onChange={e=>change("due",e.target.value)}/></label><label>Reward in credits<input className="reward-input" type="text" inputMode="numeric" pattern="[0-9]+" required value={draft.reward} onChange={e=>change("reward",e.target.value)} aria-describedby="reward-help"/></label><div className="preset-row">{[25,50,75,100].map(n=><button type="button" className="chip" key={n} onClick={()=>change("reward",String(n))}>{n}</button>)}</div><p id="reward-help">Enter any whole amount from 1 to 100,000 within your balance. These shortcuts aren’t market recommendations.</p><label>Public reference photos (up to 4)<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>F(Array.from(e.target.files||[]).slice(0,4))}/></label><small>Images are public links. Keep personal information and meeting details out of them. Files must be selected again after reloading.</small></>}
 {step===3&&<div className="review"><h2>{draft.title}</h2><p className="pre-wrap">{draft.description}</p><h3>Completion</h3><p>{draft.criteria}</p><dl><dt>Time</dt><dd>{draft.minutes} minutes</dd><dt>Where</dt><dd>{draft.mode==="remote"?"Remote":draft.location}</dd><dt>Deadline</dt><dd>{draft.due?new Date(draft.due).toLocaleString():"Flexible"}</dd><dt>Reward</dt><dd>{draft.reward} credits</dd></dl><p>Incoming offers require your review. Publishing does not reserve credits.</p></div>}
 {error&&<p role="alert" className="inline-error">{error}</p>}<div className="actions">{step>1&&<button className="secondary" type="button" disabled={busy} onClick={()=>S(step-1)}>Back</button>}<button className="primary" disabled={busy||!catalog.length}>{busy?"Publishing…":step===3?"Publish bounty":"Continue →"}</button></div></div><aside className="post-summary"><p className="eyebrow">YOUR REWARD</p><strong>{draft.reward||"—"} <small>credits</small></strong><dl><dt>Available</dt><dd>{balance??"—"}</dd><dt>After accepting an offer</dt><dd>{balance===null?"—":balance-(Number(draft.reward)||0)}</dd></dl><p>Credits are reserved when you accept an offer and transferred after completion review.</p><small>No payments or cash value.</small></aside></form></section>;
}

