"use client";
import { useEffect,useState } from "react";
import { createClient } from "../../lib/supabase/client";
import { rpc,type Profile } from "../../lib/data";
import { errorMessage } from "../../lib/rules";
import { updateMyProfileDetails,uploadProfileAvatar } from "../../lib/marketplace";
export function ProfileForm({profile,onSaved,onSignOut}:{profile:Profile;onSaved:()=>Promise<void>;onSignOut:()=>Promise<void>}){
 const [p,P]=useState(profile),[first,F]=useState(""),[last,L]=useState(""),[skills,S]=useState(profile.skills.join(", ")),[interests,I]=useState(profile.interests.join(", ")),[error,E]=useState(""),[busy,B]=useState(false);
 useEffect(()=>{createClient().from("profile_names").select("first_name,last_name").eq("profile_id",profile.id).maybeSingle().then(({data,error})=>{if(error)E(error.message);if(data){F(data.first_name);L(data.last_name);}});},[profile.id]);
 async function save(e:React.FormEvent){e.preventDefault();B(true);E("");try{if(first.trim())await rpc("save_my_names",{p_first:first,p_last:last});await updateMyProfileDetails({displayName:p.display_name,bio:p.bio||"",skills:skills.split(",").map(s=>s.trim()).filter(Boolean),interests:interests.split(",").map(s=>s.trim()).filter(Boolean),experience:p.experience,major:p.major||"",graduationYear:p.graduation_year,avatarUrl:p.avatar_url||""});await onSaved();}catch(e){E(errorMessage(e));}finally{B(false);}}
 return <section className="page-shell"><p className="eyebrow">YOUR PROFILE</p><div className="page-title"><div><h1>Let your skills speak.</h1><p>Your existing display name is preserved. Private name fields are optional for existing accounts.</p></div><button className="secondary" onClick={()=>void onSignOut()}>Sign out</button></div><form className="profile-form panel" onSubmit={save}><div className="avatar-edit">{p.avatar_url?<img alt="Your profile" src={p.avatar_url}/>:<div className="avatar-placeholder" aria-label="Profile initials">{p.display_name.slice(0,1)}</div>}<label>Profile photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;B(true);try{const url=await uploadProfileAvatar(file);P({...p,avatar_url:url});}catch(e){E(errorMessage(e));}finally{B(false);}}}/></label><small>Profile photos use public image links.</small></div><div><div className="field-row"><label>First name<input autoComplete="given-name" value={first} maxLength={80} onChange={e=>F(e.target.value)}/></label><label>Last name<input autoComplete="family-name" value={last} maxLength={80} onChange={e=>L(e.target.value)}/></label></div><small>Private. Leave last name blank if you use one name.</small><label>Public display name<input required minLength={2} maxLength={60} value={p.display_name} onChange={e=>P({...p,display_name:e.target.value})}/></label><div className="field-row"><label>Major (optional)<input maxLength={100} value={p.major||""} onChange={e=>P({...p,major:e.target.value})}/></label><label>Graduation year (optional)<input type="number" min="2024" max="2040" value={p.graduation_year||""} onChange={e=>P({...p,graduation_year:e.target.value?Number(e.target.value):null})}/></label></div><label>Bio<textarea maxLength={500} value={p.bio||""} onChange={e=>P({...p,bio:e.target.value})}/></label><label>Skills (comma-separated, up to 12)<input value={skills} onChange={e=>S(e.target.value)}/></label><label>Interests (comma-separated, up to 12)<input value={interests} onChange={e=>I(e.target.value)}/></label><label>Experience<select value={p.experience} onChange={e=>P({...p,experience:e.target.value as Profile["experience"]})}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?"Saving…":"Save profile"}</button></div></form></section>;
}
