"use client";
import { useEffect,useRef,useState } from "react";
import { createClient } from "../../lib/supabase/client";
import { rpc,type Bounty,type Offer } from "../../lib/data";
import { errorMessage,formatDate,parseReward } from "../../lib/rules";
import { Dialog } from "./Dialog";
import { SupportForm } from "./SupportForm";
import { uploadBountyImages } from "../../lib/marketplace";
import { Rating } from "./Rating";
import { ApplicationChat } from "./ApplicationChat";
type Person={id:string;display_name:string;skills:string[];bio:string|null;experience:string;rating:number|null;review_count:number;completed_count:number};
export function TaskDetail({bounty:b,userId,balance,offers,refresh,onMessage}:{bounty:Bounty;userId:string;balance:number|null;offers:Offer[];refresh:()=>Promise<void>;onMessage:(message:string)=>void}){
 const owner=b.creator_id===userId,helper=b.accepted_by===userId,participant=owner||helper;
 const [error,E]=useState(""),[busy,B]=useState(false),[editing,ED]=useState(false),[offering,OF]=useState(false),[report,R]=useState(false),[confirm,C]=useState<{label:string;action:()=>Promise<void>}|null>(null);
 const [draft,D]=useState({title:b.title,description:b.description,reward:String(b.reward_credits),criteria:b.completion_criteria,minutes:String(b.estimated_minutes||30),due:b.due_at?new Date(Date.parse(b.due_at)-new Date(b.due_at).getTimezoneOffset()*60000).toISOString().slice(0,16):""});
 const [meeting,ME]=useState<string|null>(null),[people,PE]=useState<Person[]>([]),[messages,MS]=useState<{id:string;sender_id:string;body:string;created_at:string}[]>([]),[images,IM]=useState<{image_url:string}[]>([]),[reviews,RE]=useState<{reviewer_id:string;rating:number;body:string}[]>([]);
 const keys=useRef(new Map<string,string>());
 const [chat,CHAT]=useState<Offer|null>(null);
 const [changes,CH]=useState<{id:string;description:string;criteria:string;reward:number;status:string}[]>([]),[proposing,PC]=useState(false),[bonus,BN]=useState("");
 useEffect(()=>{createClient().from("bounty_changes").select("id,description,criteria,reward,status").eq("bounty_id",b.id).eq("status","pending").then(({data,error})=>{if(error)E(error.message);else CH(data||[]);});},[b.id,b.revision,b.status,busy]);
 const token=(action:string)=>{if(!keys.current.has(action))keys.current.set(action,crypto.randomUUID());return keys.current.get(action)!;};
 async function load(){try{const db=createClient();const [m,p,i,r]=await Promise.all([db.from("bounty_messages").select("id,sender_id,body,created_at").eq("bounty_id",b.id).order("created_at",{ascending:false}).limit(100),rpc<Person[]>("get_task_people",{p_bounty:b.id}),db.from("bounty_images").select("image_url").eq("bounty_id",b.id),db.from("bounty_reviews").select("reviewer_id,rating,body").eq("bounty_id",b.id)]);if(m.error)throw m.error;if(i.error)throw i.error;if(r.error)throw r.error;MS((m.data||[]).reverse());PE(p);IM(i.data||[]);RE(r.data||[]);if(participant)ME(await rpc<string|null>("get_meeting_details",{p_bounty:b.id}));}catch(e){E(errorMessage(e));}}
 useEffect(()=>{void load();},[b.id,b.status]);
 async function run(action:()=>Promise<unknown>,message:string){B(true);E("");try{await action();await refresh();await load();onMessage(message);C(null);OF(false);ED(false);}catch(e){E(errorMessage(e));}finally{B(false);}}
 const manage=(action:string)=>rpc("manage_bounty",{p_bounty:b.id,p_action:action});
 const name=(id:string)=>people.find(p=>p.id===id)?.display_name||"Student";
 return <><div className="page-title"><div><p className="eyebrow">{b.category} · {b.status.toUpperCase()}</p><h1>{b.title}</h1><p>Posted by <span className="initials-badge">{name(b.creator_id)}</span> · {formatDate(b.created_at)}</p><Rating rating={people.find(p=>p.id===b.creator_id)?.rating??null} count={Number(people.find(p=>p.id===b.creator_id)?.review_count||0)}/></div><div className="detail-reward"><strong>{b.reward_credits.toLocaleString()}</strong><span>credits</span></div></div>{error&&<p role="alert" className="inline-error">{error}</p>}
 <div className="detail-layout"><div><section className="panel"><h2>The task</h2><p className="pre-wrap">{b.description}</p><h3>What completion looks like</h3><p>{b.completion_criteria||"Ask the poster to clarify the expected result."}</p><div className="task-meta"><span>{b.estimated_minutes?`${b.estimated_minutes} minutes estimated`:"Duration not specified"}</span><span>{b.location_type==="remote"?"Remote":b.location_name||"On campus"}</span><span>{formatDate(b.due_at)}</span></div>{meeting&&<aside className="recommendation"><h3>Private meeting details</h3><p>{meeting}</p></aside>}{images.length>0&&<div className="task-images">{images.map(i=><a key={i.image_url} href={i.image_url} target="_blank" rel="noreferrer"><img src={i.image_url} alt="Task reference"/></a>)}</div>}</section>
 {owner&&offers.length>0&&<section className="panel"><h2>Applications</h2><p>You choose who takes the task. Compare relevant skills, availability, and completed-task feedback.</p>{offers.map(o=><article className="offer" key={o.id}><h3><span className="initials-badge">{name(o.bidder_id)}</span></h3><Rating rating={people.find(p=>p.id===o.bidder_id)?.rating??null} count={Number(people.find(p=>p.id===o.bidder_id)?.review_count||0)}/><p>{people.find(p=>p.id===o.bidder_id)?.skills.join(" · ")}</p><small>{people.find(p=>p.id===o.bidder_id)?.completed_count||0} completed tasks · {people.find(p=>p.id===o.bidder_id)?.experience||"Experience not specified"}</small><p className="pre-wrap">{o.message}</p><small>{o.status}{o.bounty_revision!==b.revision?" · Task changed: this application needs renewal":""}</small><div className="actions"><button className="secondary" onClick={()=>CHAT(o)}>Message applicant</button>{b.status==="open"&&o.status==="pending"&&<button className="primary" disabled={busy||o.bounty_revision!==b.revision} onClick={()=>C({label:`Choose this applicant and reserve ${b.reward_credits} credits?`,action:()=>run(()=>rpc("accept_proposal",{p_proposal_id:o.id,p_idempotency_key:token(`accept:${o.id}`)}),"Applicant selected. The reward is reserved.")})}>Choose this helper</button>}</div></article>)}</section>}
 {participant&&b.accepted_by&&<section className="panel"><div className="section-heading"><h2>Task conversation</h2><button className="text-button" onClick={()=>void load()}>Refresh</button></div><p>Coordinate with {name(owner?b.accepted_by:b.creator_id)}. Keep changes and completion notes here.</p><div className="messages">{messages.length?messages.map(m=><article key={m.id} className={m.sender_id===userId?"own-message":""}><small>{name(m.sender_id)} · {formatDate(m.created_at)}</small><p>{m.body}</p></article>):<p>No messages yet.</p>}</div>{["accepted","submitted","disputed"].includes(b.status)&&<form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const body=new FormData(form).get("body")?.toString()||"";void run(async()=>{const {error}=await createClient().from("bounty_messages").insert({bounty_id:b.id,sender_id:userId,body});if(error)throw error;form.reset();},"Message sent.");}}><label>Message<textarea name="body" required maxLength={2000} rows={3}/></label><button className="primary" disabled={busy}>Send message</button></form>}</section>}
 {b.status==="completed"&&<section className="panel"><h2>Completed-task feedback</h2>{reviews.map(r=><article key={r.reviewer_id}><strong>{r.rating}/5 · {name(r.reviewer_id)}</strong><p>{r.body}</p></article>)}{participant&&!reviews.some(r=>r.reviewer_id===userId)&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{const {error}=await createClient().from("bounty_reviews").insert({bounty_id:b.id,reviewer_id:userId,rating:Number(f.get("rating")),body:f.get("body")});if(error)throw error;},"Review saved.");}}><label>Rating<select name="rating">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} out of 5</option>)}</select></label><label>How did the task go?<textarea name="body" required maxLength={1000}/></label><button className="primary" disabled={busy}>Submit review</button></form>}</section>}
 {participant&&changes.length>0&&b.status==="accepted"&&<section className="panel"><h2>Proposed change</h2>{changes.map(c=><article key={c.id}><p>{c.description}</p><p>Completion: {c.criteria}</p><strong>{b.reward_credits} → {c.reward} credits</strong>{helper?<div className="actions"><button className="primary" disabled={busy} onClick={()=>C({label:`Accept this scope and a total reward of ${c.reward} credits?`,action:()=>run(()=>rpc("respond_bounty_change",{p_change:c.id,p_accept:true,p_request:token(c.id)}),"New agreement accepted.")})}>Accept change</button><button className="secondary" disabled={busy} onClick={()=>run(()=>rpc("respond_bounty_change",{p_change:c.id,p_accept:false,p_request:token(c.id)}),"Change declined. The original agreement remains.")}>Decline</button></div>:<p>Waiting for the helper. Your current agreement remains in effect.</p>}</article>)}</section>}
 {owner&&b.status==="open"&&images.length<4&&<section className="panel"><label>Add public reference photos<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{const files=Array.from(e.target.files||[]).slice(0,4-images.length);if(files.length)void run(()=>uploadBountyImages(b.id,files),"Reference photos uploaded.");}} disabled={busy}/></label><small>Do not include personal information or exact meeting details.</small></section>}
 </div><aside className="panel task-actions"><h2>Your next step</h2>{b.status==="open"?<>{owner?<><p>Review offers to choose a helper. Your credits remain available until you accept an offer.</p><button className="primary" onClick={()=>ED(true)}>Edit details or reward</button><button className="secondary" disabled={busy} onClick={()=>run(()=>manage("snooze"),"Reminders snoozed for three days.")}>Remind me in 3 days</button><button className="text-button" disabled={busy||b.reminders_dismissed} onClick={()=>run(()=>manage("dismiss"),"Reminders turned off for this bounty.")}>{b.reminders_dismissed?"Reminders off":"Turn off task reminders"}</button><button className="text-button" onClick={()=>C({label:"Close this unassigned bounty? No credits are reserved.",action:()=>run(()=>manage("cancel"),"Bounty closed.")})}>No longer needed</button></>:<><p>Tell the poster how you can help and when you’re available. The reward is {b.reward_credits} credits.</p><button className="primary" onClick={()=>OF(true)}>{offers.some(o=>o.bidder_id===userId)?"Update your application":"Apply to help"}</button></>}</>:<p>{b.status==="accepted"?"Coordinate the work, then the helper can submit it for review.":b.status==="submitted"?"The poster should review the completed work before transferring credits.":b.status==="disputed"?"Credits remain reserved. Contact support with the task details for review.":`This bounty is ${b.status}.`}</p>}
 {owner&&b.status==="accepted"&&<button className="secondary" onClick={()=>PC(true)}>Propose scope or reward change</button>}
 {owner&&b.status==="completed"&&<form onSubmit={e=>{e.preventDefault();try{const amount=parseReward(bonus);C({label:`Send an additional ${amount} credits? This bonus is separate from the completed reward.`,action:()=>run(()=>rpc("bonus_bounty",{p_bounty:b.id,p_amount:amount,p_request:token(`bonus:${amount}`)}),"Additional bonus sent.")});}catch(e){E(errorMessage(e));}}}><label>Optional bonus (credits)<input inputMode="numeric" pattern="[0-9]+" required value={bonus} onChange={e=>BN(e.target.value)}/></label><small>Available: {balance??"—"}. The agreed reward has already been paid.</small><button className="secondary" disabled={busy}>Review bonus</button></form>}
 {helper&&b.status==="accepted"&&<button className="primary" disabled={busy} onClick={()=>C({label:"Submit this task for the poster’s review?",action:()=>run(()=>rpc("submit_bounty",{p_bounty_id:b.id}),"Task submitted for review.")})}>Submit completed work</button>}
 {owner&&b.status==="submitted"&&<><button className="primary" disabled={busy} onClick={()=>C({label:`Confirm completion and transfer ${b.reward_credits} reserved credits?`,action:()=>run(()=>rpc("complete_bounty",{p_bounty_id:b.id,p_idempotency_key:token("complete")}),"Completion confirmed. Credits transferred.")})}>Confirm completion</button><button className="secondary" disabled={busy} onClick={()=>run(()=>manage("request_changes"),"Changes requested. Explain what’s needed in the conversation.")}>Request changes</button></>}
 {participant&&["accepted","submitted"].includes(b.status)&&<button className="text-button" onClick={()=>C({label:"Open a dispute and keep credits reserved for review?",action:()=>run(()=>manage("dispute"),"Dispute opened. Send support the relevant details.")})}>Open a dispute</button>}
 {!owner&&offers.find(o=>o.bidder_id===userId)&&<button className="secondary" onClick={()=>CHAT(offers.find(o=>o.bidder_id===userId)!)}>Contact poster</button>}<hr/><button className="text-button" onClick={()=>R(true)}>Report this bounty</button>{!owner&&<button className="text-button" onClick={()=>C({label:"Block new offers and messages with this poster? Existing task obligations remain.",action:()=>run(async()=>{const {error}=await createClient().from("profile_blocks").upsert({blocker_id:userId,blocked_id:b.creator_id});if(error)throw error;},"Poster blocked. Contact support for any existing task issue.")})}>Block poster</button>}<small>Exact meeting details are private to task participants.</small></aside></div>
 {confirm&&<Dialog title="Review your action" onClose={()=>C(null)}><p>{confirm.label}</p><div className="actions"><button className="secondary" onClick={()=>C(null)}>Back</button><button className="primary" disabled={busy} onClick={()=>void confirm.action()}>{busy?"Saving…":"Confirm"}</button></div>{error&&<p role="alert">{error}</p>}</Dialog>}
 {report&&<Dialog title="Report a concern" onClose={()=>R(false)}><SupportForm bountyId={b.id}/></Dialog>}
 {chat&&<ApplicationChat proposalId={chat.id} userId={userId} peer={name(owner?chat.bidder_id:b.creator_id)} canSend={["pending","accepted"].includes(chat.status)&&["open","accepted","submitted"].includes(b.status)} onClose={()=>CHAT(null)}/>}
 {proposing&&<Dialog title="Propose a new agreement" onClose={()=>PC(false)}><p>Your helper must accept before anything changes. The reward cannot be reduced.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await rpc("propose_bounty_change",{p_bounty:b.id,p_description:f.get("description"),p_criteria:f.get("criteria"),p_reward:parseReward(String(f.get("reward")))});PC(false);},"Proposal sent. The current agreement remains until accepted.");}}><label>Proposed scope<textarea name="description" required minLength={20} maxLength={3000} defaultValue={b.description}/></label><label>Completion criteria<textarea name="criteria" required maxLength={1000} defaultValue={b.completion_criteria}/></label><label>Total reward (credits)<input name="reward" inputMode="numeric" pattern="[0-9]+" required defaultValue={b.reward_credits}/></label><button className="primary" disabled={busy}>Send proposal</button>{error&&<p role="alert">{error}</p>}</form></Dialog>}
 {offering&&<Dialog title="Apply to help" onClose={()=>OF(false)}><p>{b.title} · {b.reward_credits} credits. Review the current scope before sending.</p><form onSubmit={e=>{e.preventDefault();const message=new FormData(e.currentTarget).get("message");void run(()=>rpc("submit_proposal",{p_bounty_id:b.id,p_message:message}),"Your application was sent.");}}><label>Relevant experience and availability<textarea required name="message" minLength={10} maxLength={1000} defaultValue={offers.find(o=>o.bidder_id===userId)?.message||""}/></label><button className="primary" disabled={busy}>Send application</button>{error&&<p role="alert">{error}</p>}</form></Dialog>}
 {editing&&<Dialog title="Edit your bounty" onClose={()=>ED(false)}><p>Existing offers must be renewed after an edit. The reward changes from {b.reward_credits} to {draft.reward||"—"} credits. Available: {balance??"—"}.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{const reward=parseReward(draft.reward);await rpc("edit_bounty",{p_bounty:b.id,p_revision:b.revision,p_title:draft.title,p_description:draft.description,p_reward:reward,p_criteria:draft.criteria,p_minutes:Number(draft.minutes),p_due:draft.due?new Date(draft.due).toISOString():null});},"Bounty updated. Helpers with existing offers were notified.");}}><label>Title<input required minLength={5} maxLength={120} value={draft.title} onChange={e=>D({...draft,title:e.target.value})}/></label><label>Details<textarea required minLength={20} maxLength={3000} value={draft.description} onChange={e=>D({...draft,description:e.target.value})}/></label><label>Completion criteria<textarea required maxLength={1000} value={draft.criteria} onChange={e=>D({...draft,criteria:e.target.value})}/></label><div className="field-row"><label>Reward (credits)<input required inputMode="numeric" pattern="[0-9]+" value={draft.reward} onChange={e=>D({...draft,reward:e.target.value})}/></label><label>Estimated minutes<input type="number" min="5" max="1440" required value={draft.minutes} onChange={e=>D({...draft,minutes:e.target.value})}/></label></div><label>Deadline (your local time)<input type="datetime-local" value={draft.due} onChange={e=>D({...draft,due:e.target.value})}/></label><button className="primary" disabled={busy}>Save changes</button>{error&&<p role="alert">{error}</p>}</form></Dialog>}
 </>;
}


