"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { createClient } from "../lib/supabase/client";
import { brand } from "../lib/brand";
import { loadBounties, defaultPreferences, enablePush, removeDevicePush, type Bounty, type Notice, type Offer, type Preferences, type Profile, type Template } from "../lib/data";
import { errorMessage, formatDate, publicName, safeReturn } from "../lib/rules";
import { Dialog } from "./components/Dialog";
import { PostForm } from "./components/PostForm";
import { TaskDetail } from "./components/TaskDetail";
import { ProfileForm } from "./components/ProfileForm";
import { SupportForm } from "./components/SupportForm";
import { Rating } from "./components/Rating";
import { track } from "../lib/metrics";
const views = ["home","browse","post","tasks","profile","help","credits","inbox","detail"] as const;
type View = typeof views[number];
const labels:Record<string,string>={home:"Home",browse:"Browse",post:"Post a bounty",tasks:"My tasks",profile:"Profile",help:"Help",credits:"Credits",inbox:"Inbox"};
const privateViews:View[]=["post","tasks","profile","inbox","detail"];
type Entry={id:string;amount:number;created_at:string;ledger_transactions:{bounty_id:string|null;type:string}|null};
export default function App(){
 const [betaMode,BETA]=useState(false);
 const [view,V]=useState<View>("home"),[taskId,TI]=useState("");
 const [user,U]=useState<{id:string;email?:string}|null>(null),[profile,P]=useState<Profile|null>(null);
 const [bounties,B]=useState<Bounty[]>([]),[catalog,C]=useState<Template[]>([]),[offers,O]=useState<Offer[]>([]),[saved,S]=useState<string[]>([]),[notices,N]=useState<Notice[]>([]);
 const [balance,BA]=useState<number|null>(null),[ledger,L]=useState<Entry[]>([]),[prefs,PR]=useState<Preferences>(defaultPreferences);
 const [login,LO]=useState(false),[signup,SU]=useState(false),[auth,A]=useState({email:"",first:"",last:"",preferred:""}),[authMessage,AM]=useState("");
 const [cooldown,CD]=useState(0),[authBusy,AB]=useState(false),[loading,LD]=useState(false),[error,E]=useState(""),[message,M]=useState(""),[menu,ME]=useState(false);
 const [query,Q]=useState(""),[category,CA]=useState("All"),[sort,SO]=useState("Newest"),[mode,MO]=useState("All"),[min,MI]=useState(""),[max,MA]=useState(""),[minutes,MT]=useState(""),[due,DU]=useState("");
 const [group,G]=useState("Posted"),[filters,F]=useState(false);const generation=useRef(0);
 const [reputation,RP]=useState<{id:string;initials:string;rating:number|null;review_count:number}[]>([]);
 const readLocation=useCallback(()=>{const p=new URLSearchParams(location.search);const next=p.get("view") as View;V(views.includes(next)?next:"home");TI(p.get("id")||"");Q(p.get("q")||"");CA(p.get("category")||"All");SO(p.get("sort")||"Newest");MO(p.get("mode")||"All");MI(p.get("min")||"");MA(p.get("max")||"");MT(p.get("minutes")||"");DU(p.get("due")||"");},[]);
 const nav=useCallback((next:View,id?:string)=>{const p=new URLSearchParams({view:next});if(id)p.set("id",id);history.pushState({},"",`/?${p}`);V(next);TI(id||"");ME(false);M("");window.scrollTo({top:0});},[]);
 const go=(next:View,id?:string)=>{if(!user&&privateViews.includes(next)){sessionStorage.setItem("bounty:return",`/?view=${next}${id?`&id=${encodeURIComponent(id)}`:""}`);LO(true);}else nav(next,id);};
 useEffect(()=>{readLocation();window.addEventListener("popstate",readLocation);let unsubscribe=()=>{};
  try{const params=new URLSearchParams(location.search),code=params.get("code");const db=createClient();db.rpc("get_beta_access_mode").then(({data,error})=>{if(error)E(error.message);else BETA(data===true);});db.auth.getUser().then(({data})=>{U(data.user);if(code){if(data.user){history.replaceState({},"",safeReturn(sessionStorage.getItem("bounty:return")||`/${location.search.replace(/([?&])code=[^&]*&?/,'$1')}`));sessionStorage.removeItem("bounty:return");readLocation();}else{E("That sign-in link expired or could not be verified. Request a new link.");LO(true);}}}).catch(e=>E(errorMessage(e)));const {data}=db.auth.onAuthStateChange((_event,session)=>U(session?.user||null));unsubscribe=()=>data.subscription.unsubscribe();
   if(params.get("error")){E("That sign-in link expired or could not be verified. Request a new link.");LO(true);}
   // createBrowserClient exchanges PKCE codes during initialization. Never redeem twice.
  }catch(e){E(errorMessage(e));}return()=>{unsubscribe();window.removeEventListener("popstate",readLocation);};},[readLocation]);
 const refresh=useCallback(async()=>{const ticket=++generation.current;if(!user){P(null);BA(null);B([]);C([]);N([]);S([]);O([]);L([]);RP([]);PR(defaultPreferences);LD(false);return;}LD(true);E("");
  try{const db=createClient();const beta=await db.rpc("get_beta_access_mode");if(beta.error)throw beta.error;BETA(beta.data===true);if(beta.data===true){const enrollment=await db.rpc("enroll_beta_tester");if(enrollment.error)throw enrollment.error;}const r=await Promise.all([
   db.from("profiles").select("id,display_name,bio,major,graduation_year,skills,interests,experience,avatar_url,verification_status,beta_access_granted").eq("id",user.id).maybeSingle(),
   loadBounties(),
   db.from("bounty_templates").select("id,title,category,guidance,default_reward_credits,required_skills,requires_location").eq("is_active",true),
   db.from("credit_accounts").select("available_balance").eq("profile_id",user.id).maybeSingle(),
   db.from("bounty_proposals").select("id,bounty_id,bidder_id,message,status,bounty_revision"),
   db.from("notifications").select("id,bounty_id,kind,message,read_at,created_at").order("created_at",{ascending:false}).limit(100),
   db.from("saved_bounties").select("bounty_id").eq("profile_id",user.id),
   db.from("notification_preferences").select("reminders_enabled,push_enabled,timezone,quiet_start,quiet_end").eq("profile_id",user.id).maybeSingle(),
   db.from("ledger_entries").select("id,amount,created_at,ledger_transactions(bounty_id,type)").order("created_at",{ascending:false}).limit(50),db.rpc("get_marketplace_reputation")]);
   if(ticket!==generation.current)return;for(const result of r)if(result.error)throw result.error;
   P(r[0].data as Profile|null);B(r[1].data as Bounty[]);C(r[2].data as Template[]);BA(r[3].data?.available_balance??null);O(r[4].data as Offer[]);N(r[5].data as Notice[]);S((r[6].data||[]).map(s=>s.bounty_id));PR(r[7].data as Preferences||defaultPreferences);L(r[8].data as unknown as Entry[]);RP(r[9].data||[]);
  }catch(e){if(ticket===generation.current)E(errorMessage(e));}finally{if(ticket===generation.current)LD(false);}},[user]);
 useEffect(()=>{void refresh();},[refresh]);
 useEffect(()=>{if(user&&(view==="browse"||view==="detail"||view==="inbox"))track(view);},[view,user]);
 useEffect(()=>{if(!user)return;const handler=()=>void refresh();window.addEventListener("focus",handler);return()=>window.removeEventListener("focus",handler);},[user,refresh]);
 useEffect(()=>{if(cooldown<1)return;const id=setInterval(()=>CD(n=>Math.max(0,n-1)),1000);return()=>clearInterval(id);},[cooldown>0]);
 useEffect(()=>{if(view!=="browse")return;const p=new URLSearchParams({view:"browse"});Object.entries({q:query,category,sort,mode,min,max,minutes,due}).forEach(([k,v])=>{if(v)p.set(k,v);});history.replaceState({},"",`/?${p}`);},[view,query,category,sort,mode,min,max,minutes,due]);
 async function sendLink(e:React.FormEvent){e.preventDefault();AB(true);AM("");try{const email=auth.email.trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))throw new Error("Enter a valid email address.");const access=await createClient().rpc("get_beta_access_mode");if(access.error)throw access.error;if(signup&&!access.data&&!email.endsWith("@ucla.edu"))throw new Error("Open beta is closed. New accounts require a UCLA email.");const display=publicName(auth.first,auth.last,auth.preferred);if(signup&&(!auth.first.trim()||display.length<2))throw new Error("Enter your name and a display name of at least two characters.");const {error}=await createClient().auth.signInWithOtp({email,options:{shouldCreateUser:signup,emailRedirectTo:`${location.origin}${safeReturn(sessionStorage.getItem("bounty:return"))}`,data:signup?{display_name:display,first_name:auth.first.trim(),last_name:auth.last.trim()}:undefined}});if(error)throw error;CD(60);AM("Check your email. Open the new link in this browser. If it doesn’t arrive, check spam or request another link after a minute.");}catch(e){AM(errorMessage(e));}finally{AB(false);}}
 async function saveTask(id:string){if(!user){go("detail",id);return;}try{const {error}=await(saved.includes(id)?createClient().from("saved_bounties").delete().eq("profile_id",user.id).eq("bounty_id",id):createClient().from("saved_bounties").insert({profile_id:user.id,bounty_id:id}));if(error)throw error;await refresh();}catch(e){E(errorMessage(e));}}
 async function savePrefs(next:Preferences){if(!user)return;try{Intl.DateTimeFormat("en",{timeZone:next.timezone});const {error}=await createClient().from("notification_preferences").upsert({...next,profile_id:user.id});if(error)throw error;PR(next);M("Notification preferences saved.");}catch(e){E(errorMessage(e));}}
 const open=bounties.filter(b=>b.status==="open"&&(!b.due_at||new Date(b.due_at)>new Date()));
 const visible=open.filter(b=>(category==="All"||b.category===category)&&`${b.title} ${b.description}`.toLowerCase().includes(query.toLowerCase())&&(mode==="All"||b.location_type===mode)&&(!min||b.reward_credits>=Number(min))&&(!max||b.reward_credits<=Number(max))&&(!minutes||(b.estimated_minutes!==null&&b.estimated_minutes<=Number(minutes)))&&(!due||(b.due_at!==null&&b.due_at.slice(0,10)<=due))).sort((a,b)=>sort==="Highest reward"?b.reward_credits-a.reward_credits:sort==="Deadline soon"?(a.due_at?Date.parse(a.due_at):Infinity)-(b.due_at?Date.parse(b.due_at):Infinity):Date.parse(b.created_at)-Date.parse(a.created_at));
 const active=bounties.filter(b=>(b.creator_id===user?.id||b.accepted_by===user?.id)&&["open","accepted","submitted","disputed"].includes(b.status));
 const reserved=bounties.filter(b=>b.creator_id===user?.id&&["accepted","submitted","disputed"].includes(b.status)).reduce((n,b)=>n+b.reward_credits,0);
 const detail=bounties.find(b=>b.id===taskId);
 const empty=(title:string,copy:string)=><div className="empty-state"><h3>{title}</h3><p>{copy}</p></div>;
 const cards=(list:Bounty[])=><div className="listing-grid">{list.map(b=><article className="listing" key={b.id}><div className="card-top"><span className="category">{b.category}</span><button className="save" aria-label={`${saved.includes(b.id)?"Unsave":"Save"} ${b.title}`} aria-pressed={saved.includes(b.id)} onClick={()=>saveTask(b.id)}>{saved.includes(b.id)?"Saved ✓":"Save +"}</button></div><h3><a href={`/?view=detail&id=${b.id}`} onClick={e=>{e.preventDefault();go("detail",b.id);}}>{b.title}</a></h3><div className="poster-line"><span className="initials-badge">{reputation.find(p=>p.id===b.creator_id)?.initials||"S"}</span><Rating rating={reputation.find(p=>p.id===b.creator_id)?.rating??null} count={Number(reputation.find(p=>p.id===b.creator_id)?.review_count||0)}/></div><p className="description">{b.description}</p><div className="task-meta"><span>{b.location_type==="remote"?"↗ Remote":`⌖ ${b.location_name||"On campus"}`}</span><span>{b.estimated_minutes?`${b.estimated_minutes} min`:"Duration not specified"}</span><span>{formatDate(b.due_at)}</span></div><footer><strong>{b.reward_credits.toLocaleString()} <small>credits</small></strong><span className="status-pill">{b.status}</span><button className="text-button" onClick={()=>go("detail",b.id)}>{b.creator_id===user?.id?"Manage bounty":"View bounty"} →</button></footer></article>)}</div>;
 return <div className="bounty-app"><a className="skip-link" href="#content">Skip to content</a><header className="topbar"><a className="wordmark" href="/" onClick={e=>{e.preventDefault();nav("home");}}>{brand.name.toLowerCase()}<span>✦</span></a><button className="menu-toggle" aria-expanded={menu} aria-controls="main-nav" onClick={()=>ME(!menu)}>Menu</button><nav id="main-nav" aria-label="Main navigation" className={menu?"expanded":""}>{(["browse","post","tasks","credits","help"] as View[]).map(v=><a key={v} href={`/?view=${v}`} aria-current={view===v?"page":undefined} onClick={e=>{e.preventDefault();go(v);}}>{labels[v]}</a>)}</nav><div className="account-nav">{user&&<button className="inbox-button" onClick={()=>nav("inbox")}>Inbox {notices.some(n=>!n.read_at)&&<span className="badge">{notices.filter(n=>!n.read_at).length}</span>}</button>}<button className="sign-button" onClick={()=>user?nav("profile"):LO(true)}>{user?"Profile":"Sign in"}</button></div></header>
 <main id="content">{betaMode&&<div className="banner" role="status">Open beta: any confirmed email can join this marketplace. Beta access is not student verification.</div>}{error&&<div className="banner error" role="alert">{error}<button onClick={()=>void refresh()}>Retry</button><button aria-label="Dismiss error" onClick={()=>E("")}>×</button></div>}{message&&<div className="banner" role="status">{message}<button aria-label="Dismiss message" onClick={()=>M("")}>×</button></div>}{user&&profile?.verification_status!=="verified"&&<div className="banner">You’re signed in. Marketplace access requires approval{profile?` (currently ${profile.verification_status})`:" and a profile"}. <button onClick={()=>nav("help")}>Get help</button></div>}{loading&&<div className="loading" role="status">Updating your marketplace…</div>}
 {view==="home"&&<>{user?<section className="page-shell"><p className="eyebrow">YOUR DAY, A LITTLE EASIER</p><div className="page-title"><div><h1>Welcome back{profile?`, ${profile.display_name}`:""}.</h1><p>{active.length} active bounties · {balance??"—"} available credits</p></div><button className="primary" onClick={()=>go("post")}>Post a bounty +</button></div>{active.length?cards(active.slice(0,3)):empty("Your next exchange starts here","Post something you need help with, or find a task that fits your day.")}</section>:<section className="hero"><div className="hero-copy"><p className="eyebrow">{betaMode?"OPEN BETA · ALL EMAIL DOMAINS WELCOME":"FOR UCLA STUDENTS · INDEPENDENT COMMUNITY"}</p><h1>Get a hand.<br/><em>Give a hand.</em></h1><p>{brand.description}</p><div className="actions"><button className="primary" onClick={()=>nav("browse")}>Find a bounty →</button><button className="secondary" onClick={()=>go("post")}>Post a bounty +</button></div><p className="hero-note">A bounty is a task with a credit reward.<br/>Earn credits by helping. Use them to ask for help.</p></div><aside className="example-card"><span className="eyebrow">AN EXAMPLE EXCHANGE</span><span className="category">Career</span><h2>A fresh pair of eyes<br/>on your resume.</h2><p>Ask a fellow student for clear, practical feedback before you apply.</p><div className="example-meta"><span>Remote</span><span>Flexible timing</span></div><div className="example-footer"><strong>You get feedback.</strong><span>They earn credits.</span></div><small>Illustration only · this is not an open listing.</small></aside></section>}
 <section className="page-shell home-section"><div className="section-heading"><div><p className="eyebrow">SMALL TASKS. USEFUL HELP.</p><h2>Find your kind of bounty.</h2></div><button className="text-button" onClick={()=>nav("browse")}>Explore marketplace →</button></div><div className="category-tiles">{["Academic","Career","Creative","Errands","Tech"].map((c,i)=><button key={c} onClick={()=>{nav("browse");CA(c);}}><span>0{i+1}</span>{c}<b>↗</b></button>)}</div>{user&&open.length>0&&cards(open.slice(0,3))}</section><section className="how-it-works page-shell"><div><span className="step-number">01</span><h3>Make the ask clear.</h3><p>Choose a task, explain the result you need, and set a credit reward.</p></div><div><span className="step-number">02</span><h3>Find the right fit.</h3><p>Review offers and agree on the details with another student.</p></div><div><span className="step-number">03</span><h3>Help comes around.</h3><p>Confirm completion to transfer credits. Use earned credits for your next ask.</p></div></section><section className="page-shell trust-section"><h2>A community built on clear expectations.</h2><p>{betaMode?"Beta testers confirm their email. University affiliation is not checked during the beta. Exact meeting details stay between task participants. Reviews follow completed work.":"University access is checked. Exact meeting details stay between task participants. Reviews follow completed work."}</p><button className="text-button" onClick={()=>nav("credits")}>How credits work →</button><button className="text-button" onClick={()=>nav("help")}>Community guidelines →</button></section></>}
 {view==="browse"&&<section className="page-shell"><div className="page-title"><div><p className="eyebrow">THE MARKETPLACE</p><h1>Help that fits your day.</h1><p>A quick favor, a useful skill, a little more time back.</p></div><button className="primary" onClick={()=>go("post")}>Post a bounty +</button></div><div className="search-row"><label className="search-label"><span className="sr-only">Search bounties</span><input type="search" placeholder="Search tasks, skills, or keywords…" value={query} onChange={e=>Q(e.target.value)}/></label><button className="secondary" aria-expanded={filters} onClick={()=>F(!filters)}>Filters</button><label><span className="sr-only">Sort bounties</span><select value={sort} onChange={e=>SO(e.target.value)}><option>Newest</option><option>Highest reward</option><option>Deadline soon</option></select></label></div><div className="filterbar">{["All","Academic","Career","Creative","Errands","Tech"].map(c=><button className={`chip ${category===c?"selected":""}`} aria-pressed={category===c} key={c} onClick={()=>CA(c)}>{c}</button>)}</div>{filters&&<div className="filter-panel"><label>Location<select value={mode} onChange={e=>MO(e.target.value)}><option>All</option><option value="remote">Remote</option><option value="campus">On campus</option></select></label><label>Minimum credits<input type="number" min="1" value={min} onChange={e=>MI(e.target.value)}/></label><label>Maximum credits<input type="number" min="1" value={max} onChange={e=>MA(e.target.value)}/></label><label>Maximum minutes<input type="number" min="5" value={minutes} onChange={e=>MT(e.target.value)}/></label><label>Due by<input type="date" value={due} onChange={e=>DU(e.target.value)}/></label><button className="text-button" onClick={()=>{Q("");CA("All");MO("All");MI("");MA("");MT("");DU("");}}>Clear filters</button></div>}{!user?<div className="empty-state"><h2>{betaMode?"Join the open beta.":"A student-only space."}</h2><p>{betaMode?"Create an account with any email, confirm it, and join the marketplace.":"Sign in to see real bounties from your university. Student task details stay inside the community."}</p><button className="primary" onClick={()=>{sessionStorage.setItem("bounty:return","/?view=browse");LO(true);}}>Sign in to browse</button></div>:<><p className="results-count">{visible.length} open bounties</p>{visible.length?cards(visible):empty("No matching bounties yet","Try a different category or clear your filters. New tasks appear as students post them.")}</>}</section>}
 {view==="post"&&user&&<PostForm catalog={catalog} balance={balance} userId={user.id} onPublished={async (id,warning)=>{await refresh();nav("detail",id);M(warning||"Your bounty is published. Review incoming offers in My tasks.");}}/>}
 {view==="detail"&&user&&<section className="page-shell"><button className="text-button back" onClick={()=>history.back()}>← Back</button>{detail?<TaskDetail key={`${detail.id}:${detail.revision}`} bounty={detail} userId={user.id} balance={balance} offers={offers.filter(o=>o.bounty_id===detail.id)} refresh={refresh} onMessage={M}/>:!loading&&empty("This bounty is unavailable","It may be outside your university, closed, or no longer accessible.")}</section>}
 {view==="tasks"&&user&&<section className="page-shell"><div className="page-title"><div><p className="eyebrow">MY TASKS</p><h1>Keep good things moving.</h1></div><button className="primary" onClick={()=>nav("post")}>Post a bounty +</button></div><div className="filterbar">{["Posted","Helping","Saved"].map(g=><button key={g} className={`chip ${g===group?"selected":""}`} onClick={()=>G(g)}>{g}</button>)}</div>{(()=>{const list=bounties.filter(b=>group==="Posted"?b.creator_id===user.id:group==="Helping"?b.accepted_by===user.id||offers.some(o=>o.bidder_id===user.id&&o.bounty_id===b.id):saved.includes(b.id));return list.length?cards(list):empty(`No ${group.toLowerCase()} bounties yet`,"Find a task that fits or post something you need help with.");})()}</section>}
 {view==="credits"&&<section className="page-shell"><p className="eyebrow">GIVE HELP. GET HELP.</p><h1>Credits keep help moving.</h1><p className="lede">Credits are internal points for exchanging help. They have no cash value and can’t be bought, withdrawn, or transferred outside task workflows.</p>{user&&<><div className="balance-grid"><div><span>Available</span><strong>{balance??"—"}</strong><p>Ready for your next accepted offer.</p></div><div><span>Reserved</span><strong>{reserved}</strong><p>Held for assigned tasks, including disputes.</p></div></div><h2>Your recent activity</h2>{ledger.length?<div className="ledger">{ledger.map(l=><div key={l.id}><span>{l.ledger_transactions?.type.replaceAll("_"," ")||"Credit entry"}<small>{formatDate(l.created_at)}</small></span><strong>{l.amount>0?"+":""}{l.amount} credits</strong>{l.ledger_transactions?.bounty_id&&<button className="text-button" onClick={()=>nav("detail",l.ledger_transactions!.bounty_id!)}>View task →</button>}</div>)}</div>:empty("No credit entries yet","Accounts start at zero unless an administrator issues a documented grant. Earn credits by completing a bounty.")}</>}<div className="faq"><details open><summary>When do credits move?</summary><p>Posting doesn’t reserve credits. Accepting an offer reserves the agreed reward. After the helper submits the work and the poster confirms completion, the credits transfer to the helper.</p></details><details><summary>What happens if a task changes?</summary><p>Open tasks can be edited. Helpers must review and renew offers after an edit. Once assigned, the agreed reward is protected. Disputed credits remain reserved for review.</p></details><details><summary>What can I use credits for?</summary><p>Offer credits on approved tasks within your university. There are no cash withdrawals or external redemption partners. No automatic credit expiration is configured.</p></details></div></section>}
 {view==="inbox"&&user&&<section className="page-shell"><p className="eyebrow">YOUR INBOX</p><h1>The next step, in one place.</h1><p>Offers, task updates, and helpful reminders.</p><div className="inbox-layout"><div>{notices.length?notices.map(n=><article className={`notice ${n.read_at?"":"unread"}`} key={n.id}><small>{formatDate(n.created_at)} · {n.kind.replaceAll("_"," ")}</small><p>{n.message}</p><div className="actions">{n.bounty_id&&<button className="text-button" onClick={()=>nav("detail",n.bounty_id!)}>View bounty →</button>}{!n.read_at&&<button className="text-button" onClick={async()=>{const {error}=await createClient().from("notifications").update({read_at:new Date().toISOString()}).eq("id",n.id);if(error)E(error.message);else await refresh();}}>Mark read</button>}</div></article>):empty("You’re all caught up","Task updates and reminders will appear here.")}</div><aside className="panel"><h2>Your notifications</h2><form onSubmit={e=>{e.preventDefault();void savePrefs(prefs);}}><label className="check-label"><input type="checkbox" checked={prefs.reminders_enabled} onChange={e=>PR({...prefs,reminders_enabled:e.target.checked})}/>Remind me about unassigned bounties</label><label>Time zone<input value={prefs.timezone} onChange={e=>PR({...prefs,timezone:e.target.value})}/></label><div className="field-row"><label>Quiet hours start<input type="number" min="0" max="23" value={prefs.quiet_start} onChange={e=>PR({...prefs,quiet_start:Number(e.target.value)})}/></label><label>Quiet hours end<input type="number" min="0" max="23" value={prefs.quiet_end} onChange={e=>PR({...prefs,quiet_end:Number(e.target.value)})}/></label></div><small>24-hour clock. Equal hours disable quiet time.</small><button className="primary">Save preferences</button></form><hr/><p>Optional push keeps you informed when this site is closed. On iPhone or iPad, add Bounty to your Home Screen first.</p><button className="secondary" onClick={async()=>{try{if(prefs.push_enabled){await removeDevicePush();await savePrefs({...prefs,push_enabled:false});}else{await enablePush(user.id);await savePrefs({...prefs,push_enabled:true});}}catch(e){E(errorMessage(e));}}}>{prefs.push_enabled?"Turn off push":"Enable task notifications"}</button><small>Turning push off applies to this account. Your in-app inbox stays available.</small></aside></div></section>}
 {view==="profile"&&user&&profile&&<ProfileForm profile={profile} onSaved={async()=>{await refresh();M("Profile saved.");}} onSignOut={async()=>{try{await removeDevicePush().catch(()=>{});const {error}=await createClient().auth.signOut({scope:"local"});if(error)throw error;sessionStorage.removeItem(`bounty:draft:${user.id}`);U(null);nav("home");}catch(e){E(errorMessage(e));}}}/>}
 {view==="help"&&<section className="page-shell"><p className="eyebrow">HELP & COMMUNITY</p><h1>A little guidance goes a long way.</h1><div className="help-layout"><div className="faq"><details open><summary>What tasks belong here?</summary><p>Use approved templates for learning support, career feedback, creative work, permitted campus errands, and basic tech help. Academic support should help someone learn—not complete assessed work for them.</p></details><details><summary>How is access verified?</summary><p>{betaMode?"During open beta, any confirmed email can receive marketplace access. This does not verify university affiliation or identity.":"A university email and the existing student verification process control new access. This is not a background check or a guarantee about another person."}</p></details><details><summary>What if something goes wrong?</summary><p>Use the task’s report action or open a dispute for assigned work. Include relevant details in a support request. Do not share passwords or sensitive personal information.</p></details><details><summary>Meeting another student</summary><p>Choose a public campus meeting point. Exact details are shared only with task participants. If someone is in immediate danger, call 911 or local emergency services.</p></details></div><div className="panel"><h2>Contact support</h2>{user?<SupportForm/>:<><p>Sign in to send a request linked to your account.</p><button className="primary" onClick={()=>LO(true)}>Sign in</button></>}</div></div></section>}
 {!user&&privateViews.includes(view)&&<section className="page-shell"><div className="empty-state"><h1>Sign in to continue.</h1><p>Task details are available to approved marketplace members.</p><button className="primary" onClick={()=>{sessionStorage.setItem("bounty:return",`/${location.search}`);LO(true);}}>Sign in</button></div></section>}
 </main><footer className="site-footer"><a href="/" className="wordmark">{brand.name.toLowerCase()}<span>✦</span></a><p>Independent UCLA student community. Internal credits only.<br/>Not affiliated with or endorsed by UCLA.</p><button className="text-button" onClick={()=>nav("help")}>Help & community ↗</button></footer>
 {login&&<Dialog title={signup?`Join ${brand.name}`:`Welcome back to ${brand.name}`} onClose={()=>LO(false)}><div className="auth-tabs"><button type="button" aria-pressed={!signup} onClick={()=>{SU(false);AM("");}}>Sign in</button><button type="button" aria-pressed={signup} onClick={()=>{SU(true);AM("");}}>Create account</button></div><p>{signup?(betaMode?"Join the beta with any email address. Confirm your email to get access.":"A little about you. Your UCLA email keeps access within the community."):"Enter your account email. We’ll send a secure sign-in link—no password needed."}</p><form onSubmit={sendLink}><label>{signup&&!betaMode?"UCLA email":"Email"}<input type="email" autoComplete="email" required value={auth.email} onChange={e=>A({...auth,email:e.target.value})} placeholder={signup&&!betaMode?"name@ucla.edu":"you@example.com"}/></label>{signup&&<><div className="field-row"><label>First name<input autoComplete="given-name" maxLength={80} required value={auth.first} onChange={e=>A({...auth,first:e.target.value})}/></label><label>Last name<input autoComplete="family-name" maxLength={80} value={auth.last} onChange={e=>A({...auth,last:e.target.value})}/></label></div><small>If you use one name, leave last name blank.</small><label>Preferred display name (optional)<input autoComplete="nickname" maxLength={60} value={auth.preferred} onChange={e=>A({...auth,preferred:e.target.value})}/></label><small>Your display preference: {publicName(auth.first,auth.last,auth.preferred)||"first name and last initial"}. Public task identities use initials. Add your major and skills later.</small></>}<button className="primary submit" disabled={authBusy||cooldown>0}>{authBusy?"Sending…":cooldown?`Request another link in ${cooldown}s`:"Send secure sign-in link"}</button>{authMessage&&<p role="status">{authMessage}</p>}</form></Dialog>}
 </div>;
}


